stopCarousel problem
MaKu-kodilla/JQuery_practice pull request #2
Opened 2018-03-25 22:09 UTC by MaKu-kodilla

Hej,

chciałbym stopować karuzelę przy najechaniu na kontener ze zdjęciami (tak aby przy ręcznej zmianie, zdjęcia się nie przesuwały automatycznie)
Masz jakiś pomysł jak to ogarnąć? siedzę i siedzę nad tym i już zabrakło mi totalnie pomysłów :/

2018-03-26 14:56 UTC, michal-bootcamp requested changes
zeby zatrzymywac interwal, zamiast tworzy funkcje wystarczy, ze `setInterval` przypiszesz do zmiennej i pozniej bedziesz mogl zatrzymywac interwal za pomoca `clearInterval(twoja-zmienna)`. 
Raczej zatrzymywalbym go po kliku na strzalke zamiast po najechaniu myszka na karuzele, ale mozesz sprobowac tez w taki sposob to rozwiazac

2018-03-26 14:56 UTC, michal-bootcamp commented on Zadanie 10.2 Budujemy własną karuzelę/js/scripts.js
> +        carouselList.css({marginLeft: '-500px'});
dodaj wciecie w liniach 26-29

2018-03-26 14:56 UTC, michal-bootcamp commented on Zadanie 10.2 Budujemy własną karuzelę/js/scripts.js
> +        carouselList.css({marginLeft: 0});
dodaj wciecie w liniach 34-37

2018-04-03 18:13 UTC, michal-bootcamp commented
Dorzucilem usuniecie niepotrzebnego kodu.
Zwroc uwage, ze karuzela dziala tak, ze jak klikne "next" to potem musze dwa razy kliknac "prev", zeby to odnioslo skutek. Analogicznie w druga strone.

2018-04-04 19:44 UTC, MaKu-kodilla commented
naprawiłem problem z uruchamianiem karuzeli w momencie kiedy najechałem na 'kontenerek' przycisku.
Ale totalnie nie mam pomysłu jak podziałać z tymi podwójnymi kliknięciami.
Zakomentowałem overflow w css. I widzę, że po pierwszym kliknięciu karuzela przenosi obrazek na daną stronę (lewą/prawą), a dopiero po drugim przekierowuje na konkretny obrazek.

Masz jakiś pomysł co z tym można zrobić?

2018-04-05 13:51 UTC, michal-bootcamp commented
przesledz linijka po linijce co robie ten kod: 
```
$('#carousel ul').animate({marginLeft: 0}, 500, function() {
            var firstItem = carouselList.find('li:first');
            var lastItem = carouselList.find('li:last');
            firstItem.before(lastItem);
            carouselList.css({marginLeft: '-500px'});
        });
```
1. wykonaj animacje marginesu do wartosci 0 (a margines juz ma wartosc 0)
2. wez pierwszy slajd z listy
3. wez ostatni slajd z listy
4. przenies ostatni slajd przed pierwszy 
5. nadaj karuzeli margines -500px

a kolejnosc powinna byc inna:
punkt 1 powinien wystapic po punkcie 5

pomoze Ci przeniesienie tej funkcji anonimowej, ktora jest callbackiem dla animate do osobnej funkcji - analogicznie jak podeslalem to w repo z karuzela z buttonami

2018-05-31 15:07 UTC, MaKu-kodilla commented
Poprawiłem wszystkie rzeczy.
Nie mam tych buttonów dalej, niestety totalnie nie mam pomysłu jak z tym podziałać.
Czy możesz mi zaakceptować to zadanie tak jak jest? :) te buttony i tak były dodatkowe w sumie.
Podziałam z nimi na tym drugim branchu jak będę miał jakiś pomysł.

2018-06-02 20:10 UTC, merged